path_to_hdf5 : '../../../../../../scratch/aalelonghi/ROM_datasets_ale/ASTEC/try_hdf5/'
where_to_save_data: '../../../../../../scratch/aalelonghi/ROM_datasets_ale/ASTEC/made_datasets/only_loca/'
indeces_training_boundaries : [1, 2]
indeces_validation_boundaries : [3, 4]
indeces_testing_boundaries : [3,4]
percentages_sampling_training : [1.0] # percentage of training trajectories with a given subsampling
percentages_sampling_validation : [1.0] # percentage of validation trajectories with a given subsampling
percentages_sampling_testing : [0.1, 0.9] # percentage of testing trajectories with a given subsampling
subsampling_training : [1] # subsamplings of trajectories in training dataset
subsampling_validation : [2] # subsamplings of trajectories in validation dataset
subsampling_testing : [3 , 3] # subsamplings of trajectories in testing dataset
device : 'cuda'
save_dictionary_per_time_lengths : false
which_normalization : 'mean_std' #min_max or mean_std
testing: true
