path_to_hdf5 : '../../../../../../../tudelft.net/staff-umbrella/eldar/ASTEC_2/ordered_hdf5/'
where_to_save_data: '../../../../../../scratch/ROM_datasets_ale/ASTEC/made_datasets/only_sbo_min_max_moving_average'
indeces_training_boundaries  : [1028, 1214, 845, 948] # It must be the boundaries, not all indeces!
indeces_validation_boundaries  : [949, 981, 983, 999] # It must be the boundaries, not all indeces!
indeces_testing_boundaries  :  [1000, 1027] # It must be the boundaries, not all indeces!
percentages_sampling_training : [0.1, 0.9] # percentage of training trajectories with a given subsampling
percentages_sampling_validation : [0.1,0.9] # percentage of validation trajectories with a given subsampling
percentages_sampling_testing : [0.1, 0.9] # percentage of testing trajectories with a given subsampling
subsampling_training : [1,1] # subsamplings of trajectories in training dataset
subsampling_validation : [1,1] # subsamplings of trajectories in validation dataset
subsampling_testing : [1 , 1] # subsamplings of trajectories in testing dataset
device : 'cpu'
save_dictionary_per_time_lengths : false
which_normalization : 'min_max' #min_max or mean_std
percentile_high_norm_min_max : 100 # takes the nth percentile of the mzximum. So if it is 100, it will take the biggest of the maxima
percentile_low_norm_min_max : 0 # takes the nth percentile of the mzximum. So if it is 100, it will take the biggest of the minima
testing: true
smoothing_method : 'moving_average'
smoothing : true
window_length_smoothing : 300
polyorder_smoothing : 3
weight_denoise_tv_chambolle : 0.1
minimum_length_acceptable_simulation : 200
