path_to_hdf5 : '../../../../../scratch/aalelonghi/ROM_datasets_ale/ASTEC/original_hdf5/'
where_to_save_data: '../../../../../scratch/aalelonghi/ROM_datasets_ale/ASTEC/'
device : 'cuda:1'
indeces_training_boundaries : [1, 41] # need to know from which dataset to extract the data
indeces_validation_boundaries : [41, 51] # need to know from which dataset to extract the data
t_W : 10 #temporal window for time subsets of time series