path_to_test_data : '../../../../../../../scratch/ROM_datasets_ale/ASTEC/made_datasets/only_loca_min_max/'
name_test_file: 'data_testing_1_3.h5' #'data_testing_582_602.h5'
path_to_model: '../../../../../../../scratch/ROM_datasets_ale/ASTEC/saved_logs/LOCA/AE_NODE/Models/also_full_reconstruction_0.01_derivative/'
device: 'cuda:1'
trajectories_to_be_plotted : [1]
autoencoding_figures : true
autoencoding_latent_figures : true
latent_prediction_figures : true
actual_fields_prediction_figures: true
actual_latent_prediction_figures: true
TF_fields_prediction_figures: true
TF_latent_prediction_figures: true
compute_TF : true
operator_actions_indeces : [1]
generate_images_error_per_time_step : false
generate_istograms : false