path_to_test_data : '../../../../../../../scratch/aalelonghi/ROM_datasets_ale/ASTEC/made_datasets/only_loca_min_max/'
name_test_file: 'data_testing_582_602.h5'
path_to_model: '../../../../../../../scratch/aalelonghi/ROM_datasets_ale/ASTEC/saved_logs/AE_NODE/Models/dataset_1_153_192_396_398_500_min_max_15_latent_0.001_lr/'
device: 'cuda'
trajectories_to_be_plotted : [587,594,601]
autoencoding_figures : true
autoencoding_latent_figures : true
latent_prediction_figures : true
actual_fields_prediction_figures: true
actual_latent_prediction_figures: true
TF_fields_prediction_figures: true
TF_latent_prediction_figures: true
compute_TF : true
operator_actions_indeces : [1]
generate_images_error_per_time_step : false
generate_istograms : false