#Training information

loss_coefficients: # coefficients that are multiplied to the loss function terms, signaling the relative importance of each [AE, TF, AUTOREGRESSIVE, TIME_GENERALIZATION]
  AE: [1,1] #first one is for the field reconstruction, second one for the latent reconstruction per shape
  TF: 1
  AR_latent: 1
  full_reconstruction: [true, 1]
  Random_DT: 1.0
  AR_latent_strength: 0.0001
  full_reconstruction_strength: 0.0001
  lambda_regularization: 0.001 #coefficients in front of the regularization term for the latent vector

loss_coefficients_not_coupled: # coefficients that are multiplied to the loss function terms when the trainin of AE and NODE is decoupled, signaling the relative importance of each [AE, TF, AUTOREGRESSIVE, TIME_GENERALIZATION]

  AE: [0,0] #first one is for the field reconstruction, second one for the latent reconstruction per shape
  TF: 1.0
  AR_latent: 1.0
  full_reconstruction: [false, 1.0]
  Random_DT: 1.0
  AR_latent_strength: 1.0
  full_reconstruction_strength: 1.0
  lambda_regularization: 0.0 #coefficients in front of the regularization term for the latent vector

k: 4 # stage of the Runge-Kutta solver for the latent dynamics
time_of_AE: 50 # number of initial epochs where only the AutoEncoder is trained, i.e., loss_coeff_TF_AR_together = [1, 0, 0, 0]. 
time_of_lr_war_up: 10 #number of epochs of the linear warm-up of the learning rate
time_only_TF : 10 #number of initial epochs after warm up where only TF and not AR approach is used
clipping: [0, 1.5] #[if 1 clipping is applied to f, maximum norm allowed to gradients]
last_time_series_weigth_AR_latent : [false, 0.9999999999] #if true, AR loss is multiplied by weights to have the last time steps weigh less
last_time_series_weigth_AR_full_reconstruction : [false, 0.9999999999] #if true, AR loss is multiplied by weights to have the last time steps weigh less
is_coupled : [true, 'NODE'] #if the AutoEncoder (AE) is trained coupled with the NODE. if false, if 'AE' the AE is trained, if 'NODE' the NODE is trained.
freeze_AE_after_a_while : [false, 0.0023, 200] # if true, AE layers are frozen during training once they reach a good enough accuracy (second entry) and window is larger than (third entry)
path_trained_AE : '../../../../../../../scratch/ROM_datasets_ale/ASTEC/saved_logs/LOCA/AE_NODE/Models/try/' #if is_coupled : [false, 'NODE'], provide the path to the models weights of the AE

autoregressive_step:
  which_technique: 'fully_autoregressive' # this can be 'TBPP_from_end', 'TBPP_from_start', 'fully_autoregressive'
auto_encoding:
  #Auto-Encoder scalar variables
  auto_encoder_scalar:
    input_dimension_encoder: 63
    output_dimension_encoder: 11 #dimension of the latent space
    list_of_neurons_encoder: [70,60,50]
    last_activation_encoder: false

    list_of_neurons_decoder: [50,60,70]
    last_activation_decoder: false
    layer_norm_encoder : [true, false, false, false, false]
    layer_norm_decoder : [true, false, false, false, false]

  #Auto-Encoder plenum
  auto_encoder_plenum:
    input_dimension_encoder: 18
    output_dimension_encoder: 5 #dimension of the latent space
    list_of_neurons_encoder: [50,50,50]
    last_activation_encoder: false

    list_of_neurons_decoder: [50,50,50]
    last_activation_decoder: false
    layer_norm_encoder : [true, false, false, false, false]
    layer_norm_decoder : [true, false, false, false, false]

  #Auto-Encoder boundaries
  auto_encoder_boundaries:
    input_dimension_encoder: 24
    output_dimension_encoder: 24 #dimension of the latent space
    list_of_neurons_encoder: []
    last_activation_encoder: false
    layer_norm_encoder : [false]

  #Auto-Encoder core
  auto_encoder_core:
    input_dimension_encoder: [4, 12, 3]  # first dimension is # of channels (one if the predicted solution is a scalar field), second is spatial dimensions per channel.
    kernel_encoder: [3,3,3] #kernels sizes of the Encoder
    filters_encoder: [16,32,64] #number of filters of the Encoder
    strides_encoder: [[1,1],[2,1],[2,1]] #strides of the Encoder
    output_dimension_encoder: 5 #dimension of the latent space
    last_activation_encoder: false

    kernel_decoder: [[3,3],[4,3],[4,3],[3,3],[3,3],[3,3]] #kernels sizes of the decoder
    filters_decoder: [64,32,16,8] #number of middle of the decoder. First one is filters_encoder[-1] and last one is input_dimension_encoder[-2]
    strides_decoder: [[1,1],[2,1],[2,1],[1,1],[1,1],[1,1]] #strides of the decoder
    last_activation_decoder: false
    group_norm_encoder : [true, false, false, false]
    group_norm_decoder : [true,false,false,false,false,false, false]

  #Auto-Encoder vessel
  auto_encoder_vessel:
    input_dimension_encoder: [18, 15, 5]  # first dimension is # of channels (one if the predicted solution is a scalar field), second is spatial dimensions per channel.
    kernel_encoder: [3,3,3] #kernels sizes of the Encoder
    filters_encoder: [16,32,64] #number of filters of the Encoder
    strides_encoder: [[1,1],[2,1],[2,1]] #strides of the Encoder
    output_dimension_encoder: 15 #dimension of the latent space
    last_activation_encoder: false

    kernel_decoder: [[3,3],[4,3],[3,3],[3,3],[3,3],[3,3]]  #kernels of the Decoder. For this, use one upsampling with kernel 4 and one with kernel 3 because of odd output
    filters_decoder: [64,32, 20, 18] #number of filters of the Decoder
    strides_decoder: [[1,1],[2,1],[2,1],[1,1],[1,1],[1,1]] #strides of the Decoder
    last_activation_decoder: false
    group_norm_encoder : [true, false, false, false]
    group_norm_decoder : [true,false,false,false,false,false, false]

  #Auto-Encoder faces
  auto_encoder_faces:
    input_dimension_encoder: [3, 16, 9]  # first dimension is # of channels (one if the predicted solution is a scalar field), second is spatial dimensions per channel.
    kernel_encoder: [3,3,3] #kernels sizes of the Encoder
    filters_encoder: [16,32,64] #number of filters of the Encoder
    strides_encoder: [[1,1],[2,2],[2,1]] #strides of the Encoder
    output_dimension_encoder: 10 #dimension of the latent space
    last_activation_encoder: false

    kernel_decoder: [[3,3],[4,3],[4,3],[3,3],[3,3],[3,3]]  #kernels sizes of the Encoder
    filters_decoder: [64,32,16,8] #number of filters of the Encoder
    strides_decoder: [[1,1],[2,2],[2,1],[1,1],[1,1],[1,1]] #strides of the Encoder
    last_activation_decoder: false
    group_norm_encoder : [true, false, false, false]
    group_norm_decoder : [true,false,false,false,false,false, false]

  # Final_reduction
  final_reduction_and_initial_increase:
    output_dimension_encoder: 6 # THIS IS THE ACTUAL FINAL REDUCED DIMENSION

    list_of_neurons_encoder: [70,50,30]
    last_activation_encoder: false

    list_of_neurons_decoder: [30,50,70]
    last_activation_decoder: false
    layer_norm_encoder : [true, false, false, false, false]
    layer_norm_decoder : [true,false,false, false, false]

#NODE
number_of_layers_f: 4 #number of hidden Dense layers which build up the function f
parameter_information: "concatenation" #how the parameter information is passed to f. either 'concatenation' or 'FiLM'
n_FiLM_conditioning : 1 #number of FiLM layers (if FiLM is chosen instead of concatenation). FiLM = 1 only applies to the latent vector
n_neurons_f: 200 #number of neurons of each layer of f
NODE: true
scaling_output_factor: [true, 0.001] #if true, a learnable parameter is multiplied by the output, which is initialized with the second dimension. if false, the second dimension is the scalar that multiplies the output of f.
layer_norm_node : [true, false, false, false, false, false]

#Global
weight_decay:

  encoder: 0.0
  dfnn: 0.0
  decoder: 0.0

# for latent progression
RK:
  '1':
    - [0, 0]
    - [0, 1]
  
  '2':
    - [0, 0, 0]
    - [1, 1, 0]
    - [0, 1/2, 1/2]
  
  '3':
    - [0, 0, 0, 0]
    - [1/2, 1/2, 0, 0]
    - [1, -1, 2, 0]
    - [0, 1/6, 2/3, 1/6]
  
  '4':
    - [0, 0, 0, 0, 0]
    - [1/2, 1/2, 0, 0, 0]
    - [1/2, 0, 1/2, 0, 0]
    - [1, 0, 0, 1, 0]
    - [0, 1/6, 1/3, 1/3, 1/6]
