#Data information
data_training_file_dinamic: 'data_training_normalized_t_W_' #use when modifying dynamically during training the dataset
data_validation_file_dinamic: 'data_validation_normalized_t_W_' #use when modifying dynamically during training the dataset
data_training_file : 'data_training_normalized_t_W_10.h5' #use when using a fixed dataset during training
data_validation_file : 'data_validation_normalized_t_W_10.h5' #use when using a fixed dataset during training
#Training information

loss_coefficients: # coefficients that are multiplied to the loss function terms, signaling the relative importance of each [AE, TF, AUTOREGRESSIVE, TIME_GENERALIZATION]
  AE: [1,1] #first one is for the field reconstruction, second one for the latent reconstruction per shape
  TF: 1
  AR: 1
  Random_DT: 1
  AR_strength: 0.0001
  lambda_regularization: 0.01 #coefficients in front of the regularization term for the latent vector

loss_coefficients_not_coupled: # coefficients that are multiplied to the loss function terms when the trainin of AE and NODE is decoupled, signaling the relative importance of each [AE, TF, AUTOREGRESSIVE, TIME_GENERALIZATION]

  AE: [0,0] #first one is for the field reconstruction, second one for the latent reconstruction per shape
  TF: 1
  AR: 1
  Random_DT: 1
  AR_strength: 0.0001
  lambda_regularization: 0.0 #coefficients in front of the regularization term for the latent vector

k: 4 # stage of the Runge-Kutta solver for the latent dynamics
time_of_AE: 10 # number of initial epochs where only the AutoEncoder is trained, i.e., loss_coeff_TF_AR_together = [1, 0, 0, 0]. In parallel of this a linear warm-up of the learning rate is performed
time_only_TF : 0 #number of initial epochs after warm up where only TF and not AR approach is used
clipping: [0, 2.5] #[if 1 clipping is applied to f, maximum norm allowed to gradients]
is_coupled : [true, 'NODE'] #if true the AutoEncoder (AE) is trained coupled with the NODE. if false, if 'AE' the AE is trained, if 'NODE' the NODE is trained.
path_trained_AE : '../../../../../../../scratch/ROM_datasets_ale/ASTEC/saved_logs/AE_NODE/Models/only_AE/' #if is_coupled : [false, 'NODE'], provide the path to the models weights of the AE


autoregressive_step:
  start_from_t0: false
  which_technique: 'fully_autoregressive' # this can be 'TBPP_from_end', 'TBPP_from_start', 'fully_autoregressive'
  TBPP_from_end_config: [1, 30, 40]  # [if 1 k_2 increases dynamically from k_2=1, number of epochs after which k_2 is increased by 1, max rvalue of k_2]
  TBPP_from_start_config: [1, 30, 40] #[if 1 k_2 increases dynamically from k_2=1, number of epochs after which k_2 is increased by 1, max rvalue of k_2]
auto_encoding:
  #Auto-Encoder scalar variables
  auto_encoder_scalar:
    input_dimension_encoder: 4
    output_dimension_encoder: 2 #dimension of the latent space
    list_of_neurons_encoder: [50,50,50]
    last_activation_encoder: false

    list_of_neurons_decoder: [50,50,50]
    last_activation_decoder: false

  #Auto-Encoder plenum
  auto_encoder_plenum:
    input_dimension_encoder: 18
    output_dimension_encoder: 5 #dimension of the latent space
    list_of_neurons_encoder: [50,50,50]
    last_activation_encoder: false

    list_of_neurons_decoder: [50,50,50]
    last_activation_decoder: false

  #Auto-Encoder boundaries
  auto_encoder_boundaries:
    input_dimension_encoder: 6
    output_dimension_encoder: 6 #dimension of the latent space
    list_of_neurons_encoder: []
    last_activation_encoder: false

  #Auto-Encoder core
  auto_encoder_core:
    input_dimension_encoder: [4, 12, 3]  # first dimension is # of channels (one if the predicted solution is a scalar field), second is spatial dimensions per channel.
    kernel_encoder: [3,3,3] #kernels sizes of the Encoder
    filters_encoder: [8,16,32] #number of filters of the Encoder
    strides_encoder: [[1,1],[2,1],[2,1]] #strides of the Encoder
    output_dimension_encoder: 5 #dimension of the latent space
    last_activation_encoder: false

    kernel_decoder: [[3,3],[4,3],[4,3],[3,3],[3,3],[3,3]] #kernels sizes of the decoder
    filters_decoder: [16,8,4,4] #number of middle of the decoder. First one is filters_encoder[-1] and last one is input_dimension_encoder[-2]
    strides_decoder: [[1,1],[2,1],[2,1],[1,1],[1,1],[1,1]] #strides of the decoder
    last_activation_decoder: false

  #Auto-Encoder vessel
  auto_encoder_vessel:
    input_dimension_encoder: [18, 15, 5]  # first dimension is # of channels (one if the predicted solution is a scalar field), second is spatial dimensions per channel.
    kernel_encoder: [3,3,3] #kernels sizes of the Encoder
    filters_encoder: [8,16,32] #number of filters of the Encoder
    strides_encoder: [[1,1],[2,1],[2,1]] #strides of the Encoder
    output_dimension_encoder: 10 #dimension of the latent space
    last_activation_encoder: false

    kernel_decoder: [[3,3],[4,3],[3,3],[3,3],[3,3],[3,3]]  #kernels of the Decoder. For this, use one upsampling with kernel 4 and one with kernel 3 because of odd output
    filters_decoder: [32,24, 20, 18] #number of filters of the Decoder
    strides_decoder: [[1,1],[2,1],[2,1],[1,1],[1,1],[1,1]] #strides of the Decoder
    last_activation_decoder: false

  #Auto-Encoder faces
  auto_encoder_faces:
    input_dimension_encoder: [3, 16, 9]  # first dimension is # of channels (one if the predicted solution is a scalar field), second is spatial dimensions per channel.
    kernel_encoder: [3,3,3] #kernels sizes of the Encoder
    filters_encoder: [8,16,32] #number of filters of the Encoder
    strides_encoder: [[1,1],[2,2],[2,1]] #strides of the Encoder
    output_dimension_encoder: 10 #dimension of the latent space
    last_activation_encoder: false

    kernel_decoder: [[3,3],[4,3],[4,3],[3,3],[3,3],[3,3]]  #kernels sizes of the Encoder
    filters_decoder: [32,16,16,8] #number of filters of the Encoder
    strides_decoder: [[1,1],[2,2],[2,1],[1,1],[1,1],[1,1]] #strides of the Encoder
    last_activation_decoder: false

  # Final_reduction
  final_reduction_and_initial_increase:
    output_dimension_encoder: 10 # THIS IS THE ACTUAL FINAL REDUCED DIMENSION

    list_of_neurons_encoder: [10,10,10]
    last_activation_encoder: false

    list_of_neurons_decoder: [10,10,10]
    last_activation_decoder: false

#NODE
n_layers_f: 2 #number of hidden Dense layers which build up the function f
parameter_information: "concatenation" #how the parameter information is passed to f. either 'concatenation' or 'FiLM'
n_FiLM_conditioning : 1 #number of FiLM layers (if FiLM is chosen instead of concatenation). FiLM = 1 only applies to the latent vector
n_neurons_f: 200 #number of neurons of each layer of f
NODE: true
scaling_output_factor: 0.1

#Global
weight_decay:

  encoder: 0.0
  dfnn: 0.0
  decoder: 0.0

# for latent progression
RK:
  '1':
    - [0, 0]
    - [0, 1]
  
  '2':
    - [0, 0, 0]
    - [1, 1, 0]
    - [0, 1/2, 1/2]
  
  '3':
    - [0, 0, 0, 0]
    - [1/2, 1/2, 0, 0]
    - [1, -1, 2, 0]
    - [0, 1/6, 2/3, 1/6]
  
  '4':
    - [0, 0, 0, 0, 0]
    - [1/2, 1/2, 0, 0, 0]
    - [1/2, 0, 1/2, 0, 0]
    - [1, 0, 0, 1, 0]
    - [0, 1/6, 1/3, 1/3, 1/6]